### ISSUE TITLE
After weeks of operation, repeated read errors from DHT22

### ISSUE THREAD

**Issue by melgard1** [bertmelis/DHT#8] opened 2018-12-27 07:23 UTC
Have a sensor project running on 4 ESP8266 for weeks reading from DHT22. Just noticed that two of them had stopped reporting. Getting repeated read errors. Both happened to stop at 21 degrees C. I was using version 2.4.2 for Arduino core for ESP8266. I saw the warning in this projects README about getting core ESP8266 from git. I switched to that approach and I'm **always** getting read errors. Had trouble running it at all. Have to get the submodule for SoftwareSerial. If that's really required may want to mention adding in options to recursively get from the repo.

Why is the warning there to use core from git instead of board manager?

I've also tried version 2.5.0 beta 2 via board manager and it consistently fails as well. Can never read from the DHT22.

**Comment by bertmelis** [comment] 2018-12-27 12:18
The warning was there because of at the time of writing "functional interrupt" was not yet merged in the stable version. I don't know what's the status now.

What's the error you're seeing? Did resetting the esp solve the issue?

**Comment by melgard1** [comment] 2018-12-27 13:20
When using 2.4.2 of esp8266 core, I wasn't trapping the error so I don't know what it was. Are the error values documented somewhere? I was only reporting when successful and it stopped reporting successful values and I hadn't noticed for days. Resetting the ESP8266 got it working again. 

I've now changed code to be dependent on 2.5.0 of esp8266 core. It never successfully reads from the DHT22 with this newer version of esp8266 core. Doesn't work with 2.5.0 beta 1, 2.5.0 beta 2, nor current git master level of esp8266 core. Any idea what's going on with that?

I'm seeing error code 1 and 3. I haven't found a reference of what the errors are.

**Comment by bertmelis** [comment] 2018-12-27 15:08
Error 1 or 3 is related to timing issues which is the only tricky part of these sensors. I haven't tested myself using the latest Arduino core.

I can't point a direct cause besides the timing of the pulse train. If you're feeling confident, you can try playing with the timings in the code. I can do it for you. (got a logic analyzer to help) 

Sorry to say, but I can't guarantee a deadline...

**Comment by bertmelis** [comment] 2018-12-27 21:14
I just tested using a Wemos D1 mini and a DHT22 (using Arduino core v2.4.2 and git). Everything worked as expected.

Just connected the ESP to the sensor, on 3.3V without a pullup.

Could it be that your sensor is broken?

**Comment by melgard1** [comment] 2018-12-28 04:20
I said it works with v2.4.2. It does not work with 2.5.0. My sensors seem to be working fine. I have 4 ESP8266 in use right now. 2 are Lolin, 2 are Amica. My sensors are DHT22, 3 are with the pull up board, 1 directly connected without a pull up resistor. It works too. They're all connected to 3.3v.

The failures with 2.4.2 was after weeks of running continuously on two of the 4. Restarting them got them working again.
Sensors are not broken.

I've switched to using the DHTesp library with 2.5.0 beta 2. It's working fine with no issues on all 4. I like the idea of the interrupt driven async approach, but it's probably not critical in my use. Reliability is critical in my use. I can't afford to have it stop working after a few weeks and I'm now dependent on 2.5.0 of core.

You should test with ESP8266 core 2.5.0.

**Comment by bertmelis** [comment] 2018-12-28 08:06
I've tested with latest git version which is practically 2.5.0-beta2.

So I can't reproduce. Obviously, a failure that happens after weeks of operation is also hard to reproduce as I don't have a clue what could be the cause.

But I'll keep searching!

(I've updated the readme, it was indeed not clear and out-of-date)

 Question: do you have other interrupt driven operations going?

**Comment by bertmelis** [comment] 2018-12-28 22:45
Good news: it's not working on my side anymore.

It surely is a timing issue. You could try the `debug_timing` branch to see how the ESP detects the pulses.
I get this pulse train:
`287 104 80 80 81 79 79 126 141 128 80 80 127 79 128 78 93 80 80 80 80 79 79 78 140 127 79 127 80 80 127 127 137 79 79 127 128 127 127 79 0 `.

The first pulse is way too long and I suspect it "eats" the second. Hence, there's one missing at the back which results in a timeout. I'll investigate a bit further and keep you updated.

**Comment by bertmelis** [comment] 2019-01-03 16:04
Please try again with the latest version. The lib should work faster (behind the scenes). I've tested with Arduino 2.5.0 on a Wemos D1 mini using a DHT22, no external pullups.

**Comment by bertmelis** [comment] 2019-01-11 21:34
@melgard1 Any feedback?

**Comment by melgard1** [comment] 2019-01-14 15:37
Hello, sorry. Haven't tried it yet. I'll try to get to it this week.

**Comment by dmelgar** [comment] 2020-05-12 01:45
Finally got around to trying it again. So far its working fine with an "Amica" ESP8266 nodemcu board. 
However, when trying to run on a similar "Lolin" ESP8266 I'm getting error 4. I see in the code that maps to "CS", but I don't know what that means. https://www.amazon.com/gp/product/B07F8759RC/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1
On the Lolin board, using DHTesp works fine.

**Comment by bertmelis** [comment] 2020-05-12 10:21
CS is checksum error. Haven't used the sensors for a while now and there has been some work on functional interrupts.

I've got some priority matters to deal with but I'll check again soon.

**Comment by bertmelis** [comment] 2020-06-06 14:43
I've updated to code to use `attachInterruptArg`. Tested on Wemos D1 mini with DHT shield.

It should work now. Feel free to reopen.

**Closed as completed by bertmelis** 2020-06-06 14:43 UTC
